### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by markspanbroek** [status-im/nim-json-rpc#119]
The CI builds have been broken since October 6th. Since then a number of failures seem to have accumulated:

1. Windows builds are failing on the installation of MinGW
2. Linux C++ builds are failing to link `stlsstream` from chronos
3. MacOS C++ builds are failing to build `stlsstream` from chronos

**Comment by markspanbroek** [comment]
@stefantalpalaru, could you perhaps share some pointers on how to fix this?

**Comment by stefantalpalaru** [comment]
The C++ linker seems to be tripped by object file order, while the C one is not.

Linking error:

```text
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /home/stefan/.cache/nim/all_d/@m..@s..@snim-chronos@schronos@sstreams@stlsstream.nim.cpp.o: in function `newTLSClientAsyncStream__eR9b1cf4pirk4ee6jXXY41w(tyObject_AsyncStreamReadercolonObjectType___g1vFFZk9aJWczzzk2oDiHUA*, tyObject_AsyncStreamWritercolonObjectType___0Rj5qhpC572sgOcxROfs8Q*, NimStringDesc*, long, unsigned short, unsigned short, unsigned char)':
/home/stefan/.cache/nim/all_d/@m..@s..@snim-chronos@schronos@sstreams@stlsstream.nim.cpp:5097: undefined reference to `x509_noanchor_init(x509_noanchor_context*, br_x509_class_ const**)'
collect2: error: ld returned 1 exit status
```

That symbol is in BearSSL:

```text
$ nm /home/stefan/.cache/nim/all_d/certs.c.o | grep x509_noanchor_init
00000000000005ee T x509_noanchor_init
```

but that object file is passed on the command line before `@m..@s..@snim-chronos@schronos@sstreams@stlsstream.nim.cpp.o` so the linker feels free to discard it because, at that point, its exported symbols are not needed yet.

Long-form explanations:

https://stackoverflow.com/questions/1095298/gcc-c-linker-errors-undefined-reference-to-vtable-for-xxx-undefined-refere/1095321#1095321

https://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking

---

The order of those object files comes from the Nim compiler that gets it from the order of imports and the order of `{.compile: ....}` pragmas, so this lack of C++ support is a limitation of using the Nim compiler as a build system.

I suggest we drop C++ support from the test suite.

**Comment by markspanbroek** [comment]
Thanks for the quick fix, @stefantalpalaru!
